### ISSUE TITLE
v3.0.1 bot buys but doesn't sell - likely user error

### ISSUE THREAD

**Issue by cjbutcher** [CryptoGnome/LimitSwap#188]
When testing on a token, bot (v3.0.1) buys, but won't trigger sell even when sell price in base is put to extremely low number.

![image](https://user-images.githubusercontent.com/7968881/116821857-8bcd2c00-ab73-11eb-8242-4a785a15ec97.png)

Exchange is Pancake v2 no custom node

**Comment by CryptoGnome** [comment]
past you tokens JSON here

**Comment by cjbutcher** [comment]
[
  {
    "SYMBOL": "CRYSTAL",
    "ADDRESS": "0x9a1cf5c28011a7172c4eae8d89b3a2c49b7d27ac",
    "BASESYMBOL": "WBNB",
    "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    "BUYAMOUNTINBASE": "0.01",
    "BUYPRICEINBASE": "0.00000000001",
    "SELLAMOUNTINTOKENS": "ALL",
    "SELLPRICEINBASE": "0.000000000000000076079",
    "MAXTOKENS": "1",
    "MOONBAG": "0",
    "SLIPPAGE": "49",
    "HASFEES": "false",
    "GAS": "BOOST",
    "BOOSTPERCENT": "0",
    "GASLIMIT": "300000",
    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "2"
  }
]

**Comment by DizzzyDnl** [comment]
The bot is trying to buy more tokens, the buyprice is 0.00000000001 or lower and the bot detects a price which is much lower. (WBNB price) The bot then checks the amount you currently have. You have more then one token so you see an output that says:
Max Position Size Reached. Advise lower the token buying price so it is lower then current price (since you want to sell)

**Comment by CryptoGnome** [comment]
fixed to check sell

**Comment by cjbutcher** [comment]
Thanks for your help team
